spring:
  application:
  name: search
  datasource:
    url: jdbc:mysql://localhost:3306/search_db
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: create
      properties:
        hibernate.timezone.default_storage: NORMALIZE_UTC
        hibernate.jdbc.time_zone: UTC
        hibernate.dialect: org.hibernate.dialect.MySQLDialect

kakao:
  api:
    key:

naver:
  api:
    client-id:
    client-secret:
    search-url: